import SiteHeader from '../components/SiteHeader'

const CONTACT_EMAIL = 'spreadmatthew2535@gmail.com'
const mapLink = place => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`
const MapLink = ({ place, children }) => <a href={mapLink(place)} target="_blank" rel="noopener noreferrer">{children}</a>

export default function AboutPage() {
  return <>
    <SiteHeader />
    <main className="about-page">
      <section className="section about-section about-page-intro"><div className="about-intro"><h1>Faith in action. Care in community.</h1><p>Welcome to our community outreach initiative! We are a dedicated student- and community-led movement united by a shared calling to serve, pray for, and support our neighbors living on the streets in Washington, D.C.</p><p>Rooted in our anchor verse, Matthew 25:31–39, and guided by Hebrews 13:1–2 and Luke 3:11, our mission is to put faith into action through direct compassion, dignity, and fellowship.</p></div><div className="about-image-slot" role="img" aria-label="Reserved space for a 25:35 outreach photo"><span>Image coming soon</span></div></section>
      <section className="section"><div className="about-highlight"><p className="eyebrow">Our upcoming initiative</p><h2>November 13–14</h2><p>This fall, we are mobilizing a two-day community care effort designed to serve 100–150 individuals across the District.</p></div><div className="about-grid"><article><p className="eyebrow">Day 1 · November 13</p><h3>Preparation day</h3><p>Hosted at the District College ministry center, volunteers will prep food and organize care packages.</p></article><article><p className="eyebrow">Day 2 · November 14</p><h3>Outreach and evangelism</h3><p>Coordinated volunteer teams will deploy directly into the community to distribute care and share the gospel with our unhoused neighbors.</p></article><article><p className="eyebrow">Where we serve</p><h3>Two D.C. locations</h3><ul><li><MapLink place="Martin Luther King Jr. Memorial Library, 901 G St NW, Washington, DC 20001">MLK Library</MapLink>/<MapLink place="Chinatown, Washington, DC">Chinatown</MapLink></li><li><MapLink place="Columbia Heights, Washington, DC">Columbia Heights</MapLink></li></ul></article><article><p className="eyebrow">What we hand out</p><h3>Practical care packages</h3><p>Cold sandwiches, mittens, scarves, wet wipes, travel-size toiletries, and feminine hygiene products.</p></article></div></section>
      <section className="section about-details"><div><h3>Partner with us</h3><p>The District College Partnership supports our prep space, student mobilization, and logistical needs.</p></div><div><h3>Volunteer</h3><p>We need <strong>60 volunteers</strong>, 30 per day, organized into focused outreach teams.</p></div><div><h3>Support</h3><p>Our <strong>$1,300–$2,000</strong> goal funds food, supplies and winter care packages. We are seeking support to provide care packages for 100–150 people.</p></div></section>
      <section className="section about-bottom"><div><p className="eyebrow">Join us</p><p>Together, we can bring hope, comfort, and practical support to those who need it most in our city.</p><p className="scripture-list">“Whatever you did for one of the least of these brothers and sisters of mine, you did for me.”<br /><span>— Matthew 25:40</span></p><div className="cash-actions"><a className="button" href="/#donate">Donate</a><a className="button secondary" href="/#volunteer">Volunteer</a></div></div><div id="contact"><p className="eyebrow">Contact us</p><h3>Questions, partnerships, or drop-offs</h3><p>Email the 25:35 team at <a href={`mailto:${CONTACT_EMAIL}`}><strong>{CONTACT_EMAIL}</strong></a>.</p></div></section>
    </main>
    <footer>25:35 · Serving neighbors with care · <strong>We are not a registered nonprofit organization. Donations are not tax-deductible.</strong></footer>
  </>
}
